SET SCHEMA FN1MI0700004;

-- readonly

CREATE VIEW TECHNICIAN_REPAIRES_INFO
AS
SELECT T.NAME, T.EGN, R.DATE, R.PRICE
FROM TECHNICIAN T, REPRAIRS R
WHERE T.ID = R.ID_TECHNICIAN;

SELECT * FROM TECHNICIAN_REPAIRES_INFO
WHERE PRICE >40;

-- updatable

CREATE VIEW V_CATEGORIES_ALL
AS
SELECT NAME,MODEL, MANUFACTURER_NAME, YEAR
FROM CATEGORIES
WHERE YEAR > '2019-01-01';

SELECT * FROM V_CATEGORIES_ALL;

INSERT INTO V_CATEGORIES_ALL(NAME,MODEL, MANUFACTURER_NAME, YEAR)
VALUES ('Furniture','Bosch', 'Whirlpool WR23MMMS', '2022-03-02');

-- check option

CREATE VIEW V_CATEGORIES_ALL_WITH_CK
AS
SELECT NAME,MODEL, MANUFACTURER_NAME, YEAR
FROM CATEGORIES
WHERE YEAR > '2019-01-01'
WITH CHECK OPTION ;

SELECT * FROM V_CATEGORIES_ALL_WITH_CK;

INSERT INTO V_CATEGORIES_ALL_WITH_CK(NAME, MODEL, MANUFACTURER_NAME, YEAR)
VALUES ('Sink','Frigidaire', 'MI1 M234','2021-04-30'); -- OK

SELECT * FROM V_CATEGORIES_ALL_WITH_CK;

INSERT INTO V_CATEGORIES_ALL_WITH_CK(NAME, MODEL, MANUFACTURER_NAME, YEAR)
VALUES ('Boiler','Tefal', 'Tefal 234L','2015-04-30');  -- NOT OK